// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJg4W6LF-c5dW-6YuFfip8uUJO0sHT6c',
    appId: '1:778372796063:web:9d2dc18d5d26883caf5caa',
    messagingSenderId: '778372796063',
    projectId: 'sextconfidential',
    authDomain: 'sextconfidential.firebaseapp.com',
    storageBucket: 'sextconfidential.appspot.com',
    measurementId: 'G-SS3MJQTBE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVcfsZPwwzBUAFgbFJiFwnTMzJM1yUWy0',
    appId: '1:778372796063:android:23813d603481321daf5caa',
    messagingSenderId: '778372796063',
    projectId: 'sextconfidential',
    storageBucket: 'sextconfidential.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5kxG8ED4fnQAAO3kAwe94iGv9VoZrakA',
    appId: '1:778372796063:ios:44e6e84a8a40bf45af5caa',
    messagingSenderId: '778372796063',
    projectId: 'sextconfidential',
    storageBucket: 'sextconfidential.appspot.com',
    iosClientId: '778372796063-0su89i40b8e3bjjsf720svg2mukuh6pa.apps.googleusercontent.com',
    iosBundleId: 'com.coderzbar.sextconfidential.sextconfidential',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5kxG8ED4fnQAAO3kAwe94iGv9VoZrakA',
    appId: '1:778372796063:ios:44e6e84a8a40bf45af5caa',
    messagingSenderId: '778372796063',
    projectId: 'sextconfidential',
    storageBucket: 'sextconfidential.appspot.com',
    iosClientId: '778372796063-0su89i40b8e3bjjsf720svg2mukuh6pa.apps.googleusercontent.com',
    iosBundleId: 'com.coderzbar.sextconfidential.sextconfidential',
  );
}
